# Generated by Django 4.2.7 on 2023-11-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='custome_age',
        ),
        migrations.AddField(
            model_name='record',
            name='customer_age',
            field=models.IntegerField(default=18, max_length=10),
            preserve_default=False,
        ),
    ]
